services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "800:80"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - postgres
    develop:
      watch:
        - path: ./src/agent/
          action: sync+restart
          target: /app/agent/
        - path: ./src/schema/
          action: sync+restart
          target: /app/schema/
        - path: ./src/service/
          action: sync+restart
          target: /app/service/

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    environment:
      - AGENT_URL=http://agent_service:800
    develop:
      watch:
        - path: ./src/client/
          action: sync+restart
          target: /app/client/
        - path: ./src/schema/
          action: sync+restart
          target: /app/schema/
        - path: streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: agentic
      POSTGRES_USER: claudio
      POSTGRES_PASSWORD: settanta9-a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
